Controllers/CartController.cs
using InForno.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InForno.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        public ActionResult ShowCart()
        {
            if (Session["cart"] == null)
            {
                ViewBag.Nocart = "Nessun prodotto nel carrello";
            }
            else
            {
                Cart cart = (Cart)Session["cart"];
                List<DetailsOrders> detailsOrdersList = new List<DetailsOrders>();
                int index = 0;
                foreach (Cart cartItem in cart.carts)
                {
                    index++;
                    DetailsOrders detailsOrders = new DetailsOrders
                    {
                        id = index,
                        idProduct = cartItem.IdProduct,
                        quatity = cartItem.qta,
                        Products = ApiInterfaceController.GetProductById(cartItem.IdProduct),
                    };
                    detailsOrdersList.Add(detailsOrders);
                }
                return View(detailsOrdersList);
            }
            return View();
        }

        public ActionResult RemoveItem(int id)
        {
            Cart cart = (Cart)Session["cart"];
            cart.carts.RemoveAt(id - 1);
            Session["cart"] = cart;
            return RedirectToAction("ShowCart");
        }
    }
}

Controllers/OrdersController.cs
using InForno.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace InForno.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private static ModelDbContext db = new ModelDbContext();

        public ActionResult CreateOrder(string address, string note)
        {
            if (address == "")
            {
                TempData["MissingAddress"] = "Inserire indirizzo di consegna";
                return RedirectToAction("ShowCart", "Cart");
            }
            else
            {
                int id = ApiInterfaceController.GetUserByUsername(User.Identity.Name).id;
                Cart cart = (Cart)Session["cart"];
                Orders order = new Orders
                {
                    idBuyer = id,
                    processed = false,
                    data = DateTime.Now,
                    notes = note,
                    address = address,
                };

                foreach (Cart cartItem in cart.carts)
                {
                    order.DetailsOrders.Add(new DetailsOrders
                    {
                        idProduct = cartItem.IdProduct,
                        quatity = cartItem.qta,
                    });
                }

                db.Orders.Add(order);
                db.SaveChanges();
                Session.Remove("cart");
                return RedirectToAction("ShowCart", "Cart"); //poi creare pagina di riepilogo ordini per utente
            }
        }

        public ActionResult AllOrdersByClient()
        {
            int id = db.Users.Where(x => x.username == User.Identity.Name).FirstOrDefault().id;
            List<Orders> orders = db.Orders.Where(x => x.idBuyer == id).OrderByDescending(x => x.data).ToList();
            return View(orders);
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        public ActionResult AllOrders()
        {
            List<Orders> orders = db.Orders.OrderByDescending(x => x.data).ToList();
            return View(orders);
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        public ActionResult OrderPrepared(int id)
        {
            Orders order = db.Orders.Where(x => x.id == id).FirstOrDefault();
            order.processed = true;
            db.Entry(order).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("AllOrders");
        }

        [HttpPost]
        public JsonResult ProcessedToday()
        {
            try
            {
                DateTime today = DateTime.Today;
                DateTime tomorrow = today.AddDays(1);
                List<Orders> tp = db.Orders.Where(x => x.processed == true && x.data >= today && x.data < tomorrow).ToList();
                List<OrdersToJson> ordersToJson = new List<OrdersToJson>();

                foreach (Orders ord in tp)
                {
                    ordersToJson.Add(new OrdersToJson
                    {
                        id = ord.id,
                        buyerUsername = db.Users.Where(x => x.id == ord.idBuyer).FirstOrDefault().username,
                    });
                };
                return Json(ordersToJson);
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult CollectedByDay(DateTime inputVal)
        {
            try
            {
                DateTime tomorrow = inputVal.AddDays(1);
                decimal totMoney = 0;
                List<Orders> tp = db.Orders.Where(x => x.processed == true && x.data >= inputVal && x.data < tomorrow).ToList();
                List<OrdersToJson> ordersToJson = new List<OrdersToJson>();

                foreach (Orders ord in tp)
                {
                    ordersToJson.Add(new OrdersToJson
                    {
                        id = ord.id,
                        buyerUsername = db.Users.Where(x => x.id == ord.idBuyer).FirstOrDefault().username,
                    });

                    foreach (DetailsOrders dt in ord.DetailsOrders)
                    {
                        decimal totDt = dt.quatity * dt.Products.price;
                        totMoney += totDt;
                    }
                };
                return Json(totMoney);
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Controllers/ProductsController.cs
using InForno.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InForno.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private static ModelDbContext db = new ModelDbContext();

        private List<SelectListItem> ingredients
        {
            get
            {
                List<SelectListItem> list = new List<SelectListItem>();
                List<Ingredients> listIng = db.Ingredients.ToList();
                foreach (Ingredients ing in listIng)
                {
                    list.Add(new SelectListItem { Text = ing.description, Value = ing.id.ToString() });
                }
                return list;
            }
        }

        private List<string> acceptedFile
        {
            get
            {
                List<string> strings = new List<string>
                {
                    ".jpeg",
                    ".jpg",
                    ".png"
                };

                return strings;
            }
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        public ActionResult CreateProduct()
        {
            ViewBag.ingredients = ingredients;
            return View();
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        [HttpPost]
        public ActionResult CreateProduct(Products p, FormCollection cheks, HttpPostedFileBase photo)
        {
            if (ModelState.IsValid)
            {
                string nomeFile = photo.FileName;
                p.photo = nomeFile;
                string ext = Path.GetExtension(photo.FileName);
                if (acceptedFile.Contains(ext))
                {
                    string pathToSave = Path.Combine(Server.MapPath("~/Content/img"), nomeFile);
                    photo.SaveAs(pathToSave);

                    List<string> selezione = cheks.GetValues("Selezione")?.ToList();
                    foreach (string s in selezione)
                    {
                        p.Products_Ingredients.Add(new Products_Ingredients { idIngredient = Convert.ToInt16(s) });
                    }
                    db.Products.Add(p);
                    db.SaveChanges();
                    ModelState.Clear();
                    ViewBag.ingredients = ingredients;
                    ViewBag.Success = "Prodotto inserito con successo";
                    return View();
                }
                else
                {
                    ViewBag.ingredients = ingredients;
                    ViewBag.Error = "Formato file non supportato";
                    return View();
                }
            }
            else
            {
                ViewBag.ingredients = ingredients;
                return View();
            }
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        public ActionResult TableEditProduct()
        {
            List<Products> p = ApiInterfaceController.GetAllProducts();
            return View(p);
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        public ActionResult EditProduct(int id)
        {
            Products p = ApiInterfaceController.GetProductById(id);
            return View(p);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public ActionResult EditProduct(Products p, HttpPostedFileBase photo)
        {
            if (ModelState.IsValid)
            {
                Products toEdit = ApiInterfaceController.db.Products.Find(p.id);
                toEdit.name = p.name;
                toEdit.price = p.price;
                if (photo != null)
                {
                    string nomeFile = photo.FileName;
                    string ext = Path.GetExtension(photo.FileName);
                    if (acceptedFile.Contains(ext))
                    {
                        toEdit.photo = nomeFile;
                        string pathToSave = Path.Combine(Server.MapPath("~/Content/img"), nomeFile);
                        photo.SaveAs(pathToSave);
                    }
                    else
                    {
                        ViewBag.Error = "Formato file non supportato";
                        return View(p);
                    }
                }
                ApiInterfaceController.db.Entry(toEdit).State = System.Data.Entity.EntityState.Modified;
                ApiInterfaceController.db.SaveChanges();
                return RedirectToAction("TableEditProduct");
            }
            else
            {
                return View(p);
            }
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        public ActionResult DeleteProduct(int id)
        {
            Products pToRemove = db.Products.Find(id);
            db.Products.Remove(pToRemove);
            db.SaveChanges();
            return RedirectToAction("TableEditProduct");
        }

        public ActionResult ShowMenu()
        {
            List<Products> p = ApiInterfaceController.GetAllProducts();
            return View(p);
        }

        public ActionResult AddToCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                Cart cart = new Cart();
                cart.IdProduct = id;
                cart.qta = quantity;
                cart.carts.Add(cart);
                Session["cart"] = cart;
            }
            else
            {
                Cart cart = (Cart)Session["cart"];
                cart.carts.Add(new Cart
                {
                    IdProduct = id,
                    qta = quantity
                });
                Session["cart"] = cart;
            }
            return RedirectToAction("ShowMenu");
        }
    }
}

Controllers/UsersController.cs
using InForno.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI.WebControls;

namespace InForno.Controllers
{
    public class UsersController : Controller
    {
        public List<SelectListItem> TipiUser
        {
            get
            {
                List<SelectListItem> list = new List<SelectListItem>
                {
                    new SelectListItem { Text = "--- ruolo ---", Value = "" },
                    new SelectListItem { Text = "SuperAdmin", Value = "SuperAdmin" },
                    new SelectListItem { Text = "Admin", Value = "Admin" },
                    new SelectListItem { Text = "User", Value = "User" }
                };
                return list;
            }
        }

        // GET: Users
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(Users u)
        {
            if (ModelState.IsValid)
            {
                u.role = "User";
                ApiInterfaceController.Register(u);
                FormsAuthentication.SetAuthCookie(u.username, true);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

        [Authorize(Roles = "SuperAdmin")]
        public ActionResult RegisterBySuperAdmin()
        {
            ViewBag.ListUser = TipiUser;
            return View();
        }

        [Authorize(Roles = "SuperAdmin")]
        [HttpPost]
        public ActionResult RegisterBySuperAdmin(Users u)
        {
            if (ModelState.IsValid)
            {
                ApiInterfaceController.Register(u);
            }
            ViewBag.ListUser = TipiUser;
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginUser l)
        {
            if (ModelState.IsValid)
            {
                bool loginResult = ApiInterfaceController.Login(l);
                if (loginResult)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Login = "Utente o password errati";
                    return View();
                }
            }
            return View();
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
            <div class="container">
                @Html.ActionLink("🍕 Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-link m-0">Ciao @User.Identity.Name</li>

                        @if (User.IsInRole("SuperAdmin"))
                        {
                            <li>@Html.ActionLink("Registra utente", "RegisterBySuperAdmin", "Users", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                        <li>@Html.ActionLink("Ingredienti", "CreateIngredient", "Ingredients", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Aggiungi Pizza", "CreateProduct", "Products", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Modifica Pizza", "TableEditProduct", "Products", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Ordini", "AllOrders", "Orders", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Users", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </div>
            </div>
        </nav>
    }

    else if (User.Identity.IsAuthenticated)

    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
            <div class="container">
                @Html.ActionLink("🍕 Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-link m-0">Ciao @User.Identity.Name</li>
                        <li>@Html.ActionLink("🚐 Ordina", "ShowMenu", "Products", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("🛒 Carrello", "ShowCart", "Cart", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("🛒 Riepilogo Ordini", "AllOrdersByClient", "Orders", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Users", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </div>
            </div>
        </nav>
    }

    else
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
            <div class="container">
                @Html.ActionLink("🍕 Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>@Html.ActionLink("Registrati", "Register", "Users", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Login", "Login", "Users", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </div>
            </div>
        </nav>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - In Forno - Designed by <a href="https://github.com/AlessioDiPretoro">Alessio</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>