Models/Ingredients.cs
namespace InForno.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Ingredients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredients()
        {
            Products_Ingredients = new HashSet<Products_Ingredients>();
        }

        public int id { get; set; }

        [StringLength(200)]
        [Display(Name = "Descrizione")]
        public string description { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_Ingredients> Products_Ingredients { get; set; }
    }
}

Controllers/IngredientsController.cs
using InForno.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InForno.Controllers
{
    [Authorize(Roles = "Admin, SuperAdmin")]
    public class IngredientsController : Controller
    {
        // GET: Ingredients
        public ActionResult CreateIngredient()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateIngredient(Ingredients i)
        {
            ApiInterfaceController.AddIngredient(i);
            ModelState.Clear();
            return View();
        }

        public ActionResult GetAllIngredients()
        {
            return PartialView("_GetAllIngredients", ApiInterfaceController.GetAllIngredient());
        }

        public ActionResult EditIngredient(int id)
        {
            Ingredients toEdit = ApiInterfaceController.db.Ingredients.Find(id);
            return View(toEdit);
        }

        //edit e delete hanno problema con relazione in altre tabelle
        [HttpPost]
        public ActionResult EditIngredient(Ingredients i)
        {
            Ingredients toEdit = ApiInterfaceController.db.Ingredients.Find(i.id);
            toEdit.description = i.description;
            ApiInterfaceController.db.Entry(toEdit).State = System.Data.Entity.EntityState.Modified;
            ApiInterfaceController.db.SaveChanges();
            return RedirectToAction("CreateIngredient");
        }

        public ActionResult DeleteIngredient(int id)
        {
            Ingredients toDelete = ApiInterfaceController.db.Ingredients.Find(id);
            ApiInterfaceController.db.Ingredients.Remove(toDelete);
            ApiInterfaceController.db.SaveChanges();
            return RedirectToAction("CreateIngredient");
        }
    }
}

Views/Ingredients/CreateIngredient.cshtml
@model InForno.Models.Ingredients

@{
    ViewBag.Title = "CreateIngredient";
}

<div class="row row-cols-1 row-cols-md-2">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <h2>Aggiungi Ingrediente</h2>
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Aggiungi" class="btn btn-secondary" />
                </div>
            </div>
        </div>
    }
    @{
        Html.RenderAction("GetAllIngredients");
    }
</div>

Views/Ingredients/EditIngredient.cshtml
@model InForno.Models.Ingredients

@{
    ViewBag.Title = "EditIngredient";
}

<h2>EditIngredient</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ingredients</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Modifica" class="btn btn-secondary" />
            </div>
        </div>
    </div>
}

Views/Ingredients/_GetAllIngredients.cshtml
@model IEnumerable<InForno.Models.Ingredients>

@if (Model != null)
{

    <div class="mt-2 m-md-0">
        <h2>Ingredienti</h2>
        <hr />
        <table class="table table-hover table-bordered container text-center">
            <tr>
                <th>Descrizione</th>
                <th>Gestione</th>
            </tr>
            @foreach (InForno.Models.Ingredients i in Model)
            {
                <tr>
                    <td>@i.description</td>
                    <td>
                        @Html.ActionLink("✒", "EditIngredient", "Ingredients", new { id = i.id }, new { @class = "btn btn-warning" })
                        @Html.ActionLink("🗑", "DeleteIngredient", "Ingredients", new { id = i.id }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        </table>
    </div>
}